#include "protocol.h"
#include <string.h>
#include <stdlib.h>
#include <arpa/inet.h>

static uint64_t htonll(uint64_t v) { const int n=1; return *(char*)&n==1?((uint64_t)htonl(v&0xFFFFFFFF)<<32)|htonl(v>>32):v; }
static uint64_t ntohll(uint64_t v) { const int n=1; return *(char*)&n==1?((uint64_t)ntohl(v&0xFFFFFFFF)<<32)|ntohl(v>>32):v; }
void protocol_init_request(request_packet_t* r, command_type_t c, const char* f, uint64_t s, uint8_t* p, uint32_t ps) { memset(r,0,sizeof(*r)); r->command_type=c; r->file_size=s; r->payload=p; r->payload_size=ps; if(f) { r->filename_length=strlen(f); if(r->filename_length<MAX_FILENAME_LEN) strcpy(r->filename,f); } }
void protocol_init_response(response_packet_t* r, status_code_t s, const char* f, uint64_t fs, uint8_t* p, uint32_t ps) { memset(r,0,sizeof(*r)); r->status=s; r->file_size=fs; r->payload=p; r->payload_size=ps; if(f) { r->filename_length=strlen(f); if(r->filename_length<MAX_FILENAME_LEN) strcpy(r->filename,f); } }
size_t protocol_request_size(request_packet_t* r) { return r?16+r->filename_length+1+r->payload_size:0; }
size_t protocol_response_size(response_packet_t* r) { return r?20+r->filename_length+1+r->payload_size:0; }
int protocol_serialize_request(request_packet_t* r, uint8_t* b, size_t s) { if(!r||!b) return -1; size_t req=protocol_request_size(r); if(s<req) return -1; size_t o=0; uint32_t c=htonl(r->command_type); memcpy(b+o,&c,4); o+=4; uint32_t fl=htonl(r->filename_length); memcpy(b+o,&fl,4); o+=4; uint64_t fs=htonll(r->file_size); memcpy(b+o,&fs,8); o+=8; if(r->filename_length>0) { memcpy(b+o,r->filename,r->filename_length); o+=r->filename_length; } b[o++]='\0'; if(r->payload&&r->payload_size>0) memcpy(b+o,r->payload,r->payload_size); return req; }
int protocol_serialize_response(response_packet_t* r, uint8_t* b, size_t s) { if(!r||!b) return -1; size_t req=protocol_response_size(r); if(s<req) return -1; size_t o=0; uint32_t st=htonl(r->status); memcpy(b+o,&st,4); o+=4; uint32_t fl=htonl(r->filename_length); memcpy(b+o,&fl,4); o+=4; uint64_t fs=htonll(r->file_size); memcpy(b+o,&fs,8); o+=8; uint32_t ps=htonl(r->payload_size); memcpy(b+o,&ps,4); o+=4; if(r->filename_length>0) { memcpy(b+o,r->filename,r->filename_length); o+=r->filename_length; } b[o++]='\0'; if(r->payload&&r->payload_size>0) memcpy(b+o,r->payload,r->payload_size); return req; }
int protocol_deserialize_request(const uint8_t* b, size_t s, request_packet_t* r) { if(!b||!r||s<16) return -1; memset(r,0,sizeof(*r)); uint32_t c; memcpy(&c,b,4); r->command_type=ntohl(c); uint32_t fl; memcpy(&fl,b+4,4); r->filename_length=ntohl(fl); uint64_t fs; memcpy(&fs,b+8,8); r->file_size=ntohll(fs); if(r->filename_length>0&&r->filename_length<MAX_FILENAME_LEN&&16+r->filename_length<s) memcpy(r->filename,b+16,r->filename_length); return 0; }
int protocol_deserialize_response(const uint8_t* b, size_t s, response_packet_t* r) { if(!b||!r||s<20) return -1; memset(r,0,sizeof(*r)); uint32_t st; memcpy(&st,b,4); r->status=ntohl(st); uint32_t fl; memcpy(&fl,b+4,4); r->filename_length=ntohl(fl); uint64_t fs; memcpy(&fs,b+8,8); r->file_size=ntohll(fs); uint32_t ps; memcpy(&ps,b+16,4); r->payload_size=ntohl(ps); if(r->filename_length>0&&r->filename_length<MAX_FILENAME_LEN&&20+r->filename_length<s) memcpy(r->filename,b+20,r->filename_length); return 0; }
void protocol_cleanup_request(request_packet_t* r) { if(r) { if(r->payload) { free(r->payload); r->payload=NULL; } } }
void protocol_cleanup_response(response_packet_t* r) { if(r) { if(r->payload) { free(r->payload); r->payload=NULL; } } }
const char* protocol_command_to_string(command_type_t c) { switch(c) { case CMD_UPLOAD: return "UPLOAD"; case CMD_DOWNLOAD: return "DOWNLOAD"; case CMD_DELETE: return "DELETE"; case CMD_LIST: return "LIST"; case CMD_INFO: return "INFO"; case CMD_EXIT: return "EXIT"; default: return "UNKNOWN"; } }
const char* protocol_status_to_string(status_code_t s) { switch(s) { case STATUS_SUCCESS: return "SUCCESS"; case STATUS_ERROR: return "ERROR"; case STATUS_FILE_NOT_FOUND: return "FILE_NOT_FOUND"; case STATUS_FILE_EXISTS: return "FILE_EXISTS"; case STATUS_PERMISSION_DENIED: return "PERMISSION_DENIED"; case STATUS_INVALID_COMMAND: return "INVALID_COMMAND"; case STATUS_PROTOCOL_ERROR: return "PROTOCOL_ERROR"; case STATUS_SERVER_ERROR: return "SERVER_ERROR"; default: return "UNKNOWN"; } }
